config/routes.rb
Rails.application.routes.draw do
  resources :page_requests

  resources :books

end

app/models/author.rb
class Author < ActiveRecord::Base
  has_many :books
end

app/models/book.rb
class Book < ActiveRecord::Base
  belongs_to :category
  belongs_to :author
  has_many :book_users
  has_many :users, through: :book_users

  def category_name
    category.try(:name)
  end

  def self.category_names_slow
    all.map(&:category_name).uniq.compact
  end

  def self.category_names_middle
    includes(:category).all.map(&:category_name).uniq.compact
  end

  def self.category_names_fast
    category_ids = uniq.pluck(:category_id)
    Category.where(id: category_ids).pluck(:name)
  end

  def self.stack_profile(type)
    output = "tmp/stackprof-cpu-#{type}.dump"
    StackProf.run(mode: :cpu, out: output, interval: 10) do
      send(run_method(type))
    end
  end

  def self.benchmark(type)
    Benchmark.bmbm(10) do |x|
      x.report(type)  { send(run_method(type)) }
    end
  end

  def self.ruby_profile(type)
    result = RubyProf.profile do
      send(run_method(type))
    end
  end

  private

  def self.run_method(method_type)
    "category_names_#{method_type}"
  end
end

app/models/book_user.rb
class BookUser < ActiveRecord::Base
  belongs_to :book
  belongs_to :user
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :books
end

app/models/page_request.rb
class PageRequest < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :book_users
  has_many :books, through: :book_users
  has_many :authors, -> { uniq }, through: :books
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  # GET /books
  # GET /books.json
  def index
    @books = if params[:speed] == 'slow'
               Book.all
             else
               params[:speed] = 'fast'
               Book.includes(:category).all
             end
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:name, :description, :author, :publisher)
    end
end

app/controllers/page_requests_controller.rb
class PageRequestsController < ApplicationController
  before_action :set_page_request, only: [:show, :edit, :update, :destroy]

  # GET /page_requests
  # GET /page_requests.json
  def index
    @page_requests = PageRequest.all
  end

  # GET /page_requests/1
  # GET /page_requests/1.json
  def show
  end

  # GET /page_requests/new
  def new
    @page_request = PageRequest.new
  end

  # GET /page_requests/1/edit
  def edit
  end

  # POST /page_requests
  # POST /page_requests.json
  def create
    @page_request = PageRequest.new(page_request_params)

    respond_to do |format|
      if @page_request.save
        format.html { redirect_to @page_request, notice: 'Page request was successfully created.' }
        format.json { render :show, status: :created, location: @page_request }
      else
        format.html { render :new }
        format.json { render json: @page_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /page_requests/1
  # PATCH/PUT /page_requests/1.json
  def update
    respond_to do |format|
      if @page_request.update(page_request_params)
        format.html { redirect_to @page_request, notice: 'Page request was successfully updated.' }
        format.json { render :show, status: :ok, location: @page_request }
      else
        format.html { render :edit }
        format.json { render json: @page_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /page_requests/1
  # DELETE /page_requests/1.json
  def destroy
    @page_request.destroy
    respond_to do |format|
      format.html { redirect_to page_requests_url, notice: 'Page request was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_page_request
      @page_request = PageRequest.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def page_request_params
      params.require(:page_request).permit(:path, :view_duration, :db_duration, :page_duration)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/page_requests_helper.rb
module PageRequestsHelper
end

app/views/books/_form.html.erb
<%= form_for(@book) do |f| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :author %><br>
    <%= f.text_field :author %>
  </div>
  <div class="field">
    <%= f.label :publisher %><br>
    <%= f.text_field :publisher %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing book</h1>

<%= render 'form' %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<h1>Listing books</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Author</th>
      <th>Publisher</th>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.name %></td>
        <td><%= book.description %></td>
        <td><%= book.author %></td>
        <td><%= book.publisher %></td>
        <td><%= book.category.name %></td>
        <td><%= link_to 'Show', book %></td>
        <td><%= link_to 'Edit', edit_book_path(book) %></td>
        <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Book', new_book_path %>

app/views/books/new.html.erb
<h1>New book</h1>

<%= render 'form' %>

<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @book.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @book.description %>
</p>

<p>
  <strong>Author:</strong>
  <%= @book.author %>
</p>

<p>
  <strong>Publisher:</strong>
  <%= @book.publisher %>
</p>

<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BookStore</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/page_requests/_form.html.erb
<%= form_for(@page_request) do |f| %>
  <% if @page_request.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@page_request.errors.count, "error") %> prohibited this page_request from being saved:</h2>

      <ul>
      <% @page_request.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :path %><br>
    <%= f.text_field :path %>
  </div>
  <div class="field">
    <%= f.label :view_duration %><br>
    <%= f.text_field :view_duration %>
  </div>
  <div class="field">
    <%= f.label :db_duration %><br>
    <%= f.text_field :db_duration %>
  </div>
  <div class="field">
    <%= f.label :page_duration %><br>
    <%= f.text_field :page_duration %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/page_requests/edit.html.erb
<h1>Editing page_request</h1>

<%= render 'form' %>

<%= link_to 'Show', @page_request %> |
<%= link_to 'Back', page_requests_path %>

app/views/page_requests/index.html.erb
<h1>Listing page_requests</h1>

<table>
  <thead>
    <tr>
      <th>Path</th>
      <th>View duration</th>
      <th>Db duration</th>
      <th>Page duration</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @page_requests.each do |page_request| %>
      <tr>
        <td><%= page_request.path %></td>
        <td><%= page_request.view_duration %></td>
        <td><%= page_request.db_duration %></td>
        <td><%= page_request.page_duration %></td>
        <td><%= link_to 'Show', page_request %></td>
        <td><%= link_to 'Edit', edit_page_request_path(page_request) %></td>
        <td><%= link_to 'Destroy', page_request, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Page request', new_page_request_path %>

app/views/page_requests/new.html.erb
<h1>New page_request</h1>

<%= render 'form' %>

<%= link_to 'Back', page_requests_path %>

app/views/page_requests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Path:</strong>
  <%= @page_request.path %>
</p>

<p>
  <strong>View duration:</strong>
  <%= @page_request.view_duration %>
</p>

<p>
  <strong>Db duration:</strong>
  <%= @page_request.db_duration %>
</p>

<p>
  <strong>Page duration:</strong>
  <%= @page_request.page_duration %>
</p>

<%= link_to 'Edit', edit_page_request_path(@page_request) %> |
<%= link_to 'Back', page_requests_path %>